# Generated by Django 4.1.7 on 2023-03-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movie_short",
            new_name="Movie_shots",
        ),
    ]
