# Generated by Django 4.1.7 on 2023-03-16 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_rating_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieShots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="movie_shots/", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кадр из фильма",
                "verbose_name_plural": "Кадры из фильма",
            },
        ),
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "Рейтинг", "verbose_name_plural": "Рейтинги"},
        ),
        migrations.AlterModelOptions(
            name="ratingstar",
            options={
                "ordering": ["-value"],
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
            },
        ),
        migrations.RemoveField(
            model_name="movie",
            name="fees_in_world",
        ),
        migrations.AddField(
            model_name="movie",
            name="fess_in_world",
            field=models.PositiveIntegerField(
                default=0,
                help_text="указывать сумму в долларах",
                verbose_name="Сборы в мире",
            ),
        ),
        migrations.AlterField(
            model_name="actor",
            name="age",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Возраст"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Категория"),
        ),
        migrations.AlterField(
            model_name="category",
            name="url",
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name="genre",
            name="url",
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="budget",
            field=models.PositiveIntegerField(
                default=0, help_text="указывать сумму в долларах", verbose_name="Бюджет"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="fees_in_usa",
            field=models.PositiveIntegerField(
                default=0,
                help_text="указывать сумму в долларах",
                verbose_name="Сборы в США",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="url",
            field=models.SlugField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="world_premiere",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Примьера в мире"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="ip",
            field=models.CharField(max_length=15, verbose_name="IP адрес"),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="text",
            field=models.TextField(max_length=5000, verbose_name="Сообщение"),
        ),
        migrations.DeleteModel(
            name="Movie_shots",
        ),
        migrations.AddField(
            model_name="movieshots",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="Фильм",
            ),
        ),
    ]
